### ISSUE TITLE
Consider renaming/rescoping the project to also deal with upcomming 1.0.0 ?

### ISSUE THREAD

**Issue by bluemmc** [dazinator/AspNetSolutionUpgradeTool#31]
I think this tool is wonderfull but I would like to use it not just for RC1-RC2 but also for RC1/2-1.0.0. The new version 1.0.0 is currently scheduled for 27th of June.

I just looked at the prelimary list of changes 1.0.0 which currently numbers about 15 breaking changes in addition to new version numbers. I therefore think this tool could be quite useful for changing to 1.0.0 also ?

**Comment by dazinator** [comment]
Thanks - I agree. All of the upgrade logic so far is basically contained within a set of `IProjectUpgradeAction`, `ICsharpCodeUpgradeAction` and `ISolutionUpgradeAction`'s. Together, the set of those is the RC1 - RC2 upgrade. I;d most likely extend the tool to only Apply this set of actions if the current global.json was RC1. I'd then define the new set for the RC2 - 1.0.0 upgrade, and get the tool to run that set after the RC1 --> RC2 upgrade completes.

**Comment by dazinator** [comment]
I will revisit this when 1.0.0 is released, and most likely rename this repository after that support is added ;)

**Comment by RehanSaeed** [comment]
The word on the street is that VS will auto upgrade from RC2 to RTM.

**Comment by dazinator** [comment]
@RehanSaeed perfect. If only they could have done that for RC1 to RC2 :(

**Comment by dazinator** [comment]
Will close this for now, on the assumption that Microsoft are indeed taking care of this

**Comment by bluemmc** [comment]
@RehanSaeed Where have you heard this? I also heard that there would be no breaking changes but now I see there are plenty.

**Comment by dazinator** [comment]
Pretty sure it was mentioned in the community standup video.

**Comment by dazinator** [comment]
Looks like its not exactly seemless.

At a minimum I could extend this tool to:

1. Upgrade the versions of packages used from RC2 to 1.0.0
2. Upgrade global.json from `preview1` to `preview2`
3. Some of this stuff for those using EF: https://docs.efproject.net/en/latest/miscellaneous/rc2-rtm-upgrade.html

**Comment by bluemmc** [comment]
Very, very nice!
